/* GestorPro Dashboard Pro V1 — KPIs e visão executiva sem alterar o modelo de dados */
(function(){
'use strict';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const arr=()=>Array.isArray(window.D?.clients)?window.D.clients:[];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function stats(){const c=arr();const active=c.filter(x=>['active','ativo','trial'].includes(String(x.status||'').toLowerCase()));const expired=c.filter(x=>['expired','vencido','inactive','inativo'].includes(String(x.status||'').toLowerCase()));const now=Date.now();const soon=c.filter(x=>{const d=new Date(x.expires_at||x.vencimento||x.due_date||x.expiration_date);return !isNaN(d)&&d>now&&d-now<=7*864e5});const revenue=c.reduce((s,x)=>s+Number(x.amount||x.valor||x.price||0),0);return {total:c.length,active:active.length,expired:expired.length,soon:soon.length,revenue}}
function render(){if(document.getElementById('gpProDashboard'))return;const host=document.querySelector('main')||document.body;const s=stats();const el=document.createElement('section');el.id='gpProDashboard';el.className='gp-pro-dashboard';el.innerHTML='<div class="gp-pro-head"><div><span class="gp-pro-kicker">VISÃO EXECUTIVA</span><h2>Resumo do painel</h2><p>Indicadores atualizados a partir dos dados carregados do sistema.</p></div><button id="gpProRefresh">↻ Atualizar</button></div><div class="gp-pro-grid"><article><span>Clientes</span><strong>'+s.total+'</strong><small>Total cadastrado</small></article><article><span>Ativos</span><strong>'+s.active+'</strong><small>Ativos ou em teste</small></article><article><span>Vencendo em 7 dias</span><strong>'+s.soon+'</strong><small>Acompanhe as cobranças</small></article><article><span>Expirados</span><strong>'+s.expired+'</strong><small>Precisam de atenção</small></article><article class="wide"><span>Valor recorrente identificado</span><strong>'+money(s.revenue)+'</strong><small>Soma dos valores encontrados nos clientes carregados</small></article></div><div class="gp-pro-note">💡 Este painel é apenas uma camada de visualização. Nenhum dado é salvo no navegador por este módulo.</div></section>';host.prepend(el);document.getElementById('gpProRefresh').onclick=()=>{el.remove();render()}}
function init(){if(window.GestorProOrganization?.role==='master'||window.GestorProOrganization){render()}}
window.addEventListener('gestorpro:auth-ready',init);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));else setTimeout(init,500);
const style=document.createElement('style');style.textContent='.gp-pro-dashboard{margin:20px auto;padding:0 18px;max-width:1280px;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.gp-pro-head{display:flex;justify-content:space-between;align-items:end;gap:15px;margin-bottom:16px}.gp-pro-kicker{font-size:11px;font-weight:900;letter-spacing:.12em;color:#6d42e8}.gp-pro-head h2{margin:4px 0;font-size:26px;color:#20182a}.gp-pro-head p{margin:0;color:#756b80}.gp-pro-head button{border:0;border-radius:10px;background:#6d42e8;color:#fff;padding:10px 14px;font-weight:800;cursor:pointer}.gp-pro-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.gp-pro-grid article{background:#fff;border:1px solid #ebe5f1;border-radius:16px;padding:18px;box-shadow:0 6px 22px rgba(32,24,42,.06)}.gp-pro-grid article span{display:block;color:#766b80;font-size:12px;font-weight:800}.gp-pro-grid strong{display:block;font-size:28px;margin:8px 0 4px;color:#21182b}.gp-pro-grid small{color:#8a8091}.gp-pro-grid .wide{grid-column:span 2}.gp-pro-note{margin-top:12px;padding:12px 14px;border-radius:12px;background:#f8f5fb;color:#665b70;font-size:12px}@media(max-width:900px){.gp-pro-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.gp-pro-grid .wide{grid-column:span 2}}@media(max-width:600px){.gp-pro-head{align-items:start;flex-direction:column}.gp-pro-grid{grid-template-columns:1fr}.gp-pro-grid .wide{grid-column:auto}}';document.head.appendChild(style);
})();
